@echo off
echo Open Watcom Build Environment
PATH C:\WC\BINNT64;C:\WC\BINNT;%%PATH%%
SET INCLUDE=C:\WC\H;C:\WC\H\NT;C:\WC\H\NT\DIRECTX;C:\WC\H\NT\DDK;%%INCLUDE%%
SET WATCOM=C:\WC
SET EDPATH=C:\WC\EDDAT
SET WHTMLHELP=C:\WC\BINNT\HELP
SET WIPFC=C:\WC\WIPFC
